;====================================================================================
;====================================================================================


Const SHOPMENU_MAIN=0

Const SHOPMENU_ABILITY=1
Const SHOPMENU_ABILITY_PURCHASE=10

Const SHOPMENU_SKILL=2
Const SHOPMENU_SKILL_PURCHASE=20

Const SHOPMENU_HANDICAP=3
Const SHOPMENU_HANDICAP_PURCHASE=30

Const SHOPMENU_CONSUME=4
Const SHOPMENU_CONSUME_PURCHASE=40

Const SHOPMENU_COSMETIC=5
Const SHOPMENU_COSMETIC_PURCHASE=50

Dim SHOPITEM_TOTAL(5)
Dim SHOPITEM_UNLOCKED(5,16)
Dim SHOPITEM_PRICE(5,16)
Dim SHOPITEM_NAME$(5,16)
Dim SHOPITEM_DESC1$(5,16)
Dim SHOPITEM_DESC2$(5,16)
Dim SHOPITEM_MULT#(5,16)

Dim SHOPITEM_ENABLED(5,16)



;====================================================================================

ab=1

Global ABILITY_RINGMAGNET = ab : ab=ab+1
Global ABILITY_SAFETYNET  = ab : ab=ab+1 
Global ABILITY_FULLYLOADED  = ab : ab=ab+1  
;Global ABILITY_EMERALDHUNTER  = ab : ab=ab+1 
;Global ABILITY_REDRINGRADAR  = ab : ab=ab+1 
;Global ABILITY_DOUBLEVALUE  = ab : ab=ab+1
;Global ABILITY_DETECTION  = ab : ab=ab+1 
Global ABILITY_SPIN  = ab : ab=ab+1 
Global ABILITY_ENDLESSGAUGE  = ab : ab=ab+1 
Global ABILITY_SPARECHANGE  = ab : ab=ab+1

SHOPITEM_TOTAL(SHOPMENU_ABILITY)=ab-1

;====================================================================================

sk=1

Global SKILL_SHIELD = sk : sk=sk+1
Global SKILL_FSHIELD = sk : sk=sk+1
Global SKILL_BSHIELD = sk : sk=sk+1 
Global SKILL_TSHIELD  = sk : sk=sk+1 
Global SKILL_ESHIELD  = sk : sk=sk+1

Global SKILL_BOOST  = sk : sk=sk+1
Global SKILL_DROPDASH  = sk : sk=sk+1
;Global SKILL_ISHIELD  = sk : sk=sk+1
;Global SKILL_CHAO  = sk : sk=sk+1
Global SKILL_DOUBLEJUMP  = sk : sk=sk+1


SHOPITEM_TOTAL(SHOPMENU_SKILL)=sk-1 

;====================================================================================

hc=1

Global HANDICAP_NOROLL = hc : hc=hc+1 
Global HANDICAP_NOJUMP = hc : hc=hc+1
Global HANDICAP_DAREDEVIL = hc : hc=hc+1 


SHOPITEM_TOTAL(SHOPMENU_HANDICAP)=hc-1  

;====================================================================================

cb=1
Global CONSUME_LIFE     = cb : cb = cb + 1 
Global CONSUME_EMBLEM   = cb : cb = cb + 1 
Global CONSUME_REDRING  = cb : cb = cb + 1

SHOPITEM_TOTAL(SHOPMENU_CONSUME)=cb-1 

;====================================================================================

cs=1

;Global COSMETIC_BIGHEAD = cs : cs=cs+1 
Global COSMETIC_FLATCHARS = cs : cs=cs+1
Global COSMETIC_INVIS = cs : cs=cs+1


SHOPITEM_TOTAL(SHOPMENU_COSMETIC)=cs-1


;====================================================================================






;Abilities
SHOPITEM_PRICE(SHOPMENU_ABILITY,ABILITY_RINGMAGNET)=500
SHOPITEM_NAME$(SHOPMENU_ABILITY,ABILITY_RINGMAGNET)="Ring Magnet"
SHOPITEM_DESC1$(SHOPMENU_ABILITY,ABILITY_RINGMAGNET)="Getting close to rings will magnetise them"
SHOPITEM_DESC2$(SHOPMENU_ABILITY,ABILITY_RINGMAGNET)="towards you just like a Lightning Shield!"
SHOPITEM_MULT#(SHOPMENU_ABILITY,ABILITY_RINGMAGNET)=0.9

SHOPITEM_PRICE(SHOPMENU_ABILITY,ABILITY_SAFETYNET)=500
SHOPITEM_NAME$(SHOPMENU_ABILITY,ABILITY_SAFETYNET)="Safety Net"
SHOPITEM_DESC1$(SHOPMENU_ABILITY,ABILITY_SAFETYNET)="Respawn with 10 rings."
SHOPITEM_DESC2$(SHOPMENU_ABILITY,ABILITY_SAFETYNET)=""
SHOPITEM_MULT#(SHOPMENU_ABILITY,ABILITY_SAFETYNET)=0.9

SHOPITEM_PRICE(SHOPMENU_ABILITY,ABILITY_FULLYLOADED)=500
SHOPITEM_NAME$(SHOPMENU_ABILITY,ABILITY_FULLYLOADED)="Fully Loaded"
SHOPITEM_DESC1$(SHOPMENU_ABILITY,ABILITY_FULLYLOADED)="Start a Stage with a full gauge."
SHOPITEM_DESC2$(SHOPMENU_ABILITY,ABILITY_FULLYLOADED)=""
SHOPITEM_MULT#(SHOPMENU_ABILITY,ABILITY_FULLYLOADED)=0.9

SHOPITEM_PRICE(SHOPMENU_ABILITY,ABILITY_EMERALDHUNTER)=1000
SHOPITEM_NAME$(SHOPMENU_ABILITY,ABILITY_EMERALDHUNTER)="Emerald Hunter"
SHOPITEM_DESC1$(SHOPMENU_ABILITY,ABILITY_EMERALDHUNTER)="Extends the range of your Emerald Radar."
SHOPITEM_DESC2$(SHOPMENU_ABILITY,ABILITY_EMERALDHUNTER)=""
SHOPITEM_MULT#(SHOPMENU_ABILITY,ABILITY_EMERALDHUNTER)=0.9

SHOPITEM_PRICE(SHOPMENU_ABILITY,ABILITY_REDRINGRADAR)=2000
SHOPITEM_NAME$(SHOPMENU_ABILITY,ABILITY_REDRINGRADAR)="Red Ring Radar"
SHOPITEM_DESC1$(SHOPMENU_ABILITY,ABILITY_REDRINGRADAR)="Activates a sound cue when a Red Ring"
SHOPITEM_DESC2$(SHOPMENU_ABILITY,ABILITY_REDRINGRADAR)="is nearby."
SHOPITEM_MULT#(SHOPMENU_ABILITY,ABILITY_REDRINGRADAR)=0.75

SHOPITEM_PRICE(SHOPMENU_ABILITY,ABILITY_DOUBLEVALUE)=1000
SHOPITEM_NAME$(SHOPMENU_ABILITY,ABILITY_DOUBLEVALUE)="Ring Doubler"
SHOPITEM_DESC1$(SHOPMENU_ABILITY,ABILITY_DOUBLEVALUE)="Each ring gives you twice the amount it"
SHOPITEM_DESC2$(SHOPMENU_ABILITY,ABILITY_DOUBLEVALUE)="usually does!"
SHOPITEM_MULT#(SHOPMENU_ABILITY,ABILITY_DOUBLEVALUE)=0.75

SHOPITEM_PRICE(SHOPMENU_ABILITY,ABILITY_DETECTION)=1000
SHOPITEM_NAME$(SHOPMENU_ABILITY,ABILITY_DETECTION)="See me Now?"
SHOPITEM_DESC1$(SHOPMENU_ABILITY,ABILITY_DETECTION)="Enemy detection range is cut in half."
SHOPITEM_DESC2$(SHOPMENU_ABILITY,ABILITY_DETECTION)="For those pesky Stealth missions."
SHOPITEM_MULT#(SHOPMENU_ABILITY,ABILITY_DETECTION)=0.9

SHOPITEM_PRICE(SHOPMENU_ABILITY,ABILITY_SPIN)=500
SHOPITEM_NAME$(SHOPMENU_ABILITY,ABILITY_SPIN)="Spin Cycle"
SHOPITEM_DESC1$(SHOPMENU_ABILITY,ABILITY_SPIN)="All characters now spin when they jump"
SHOPITEM_DESC2$(SHOPMENU_ABILITY,ABILITY_SPIN)="for extra protection and badnik bouncing."
SHOPITEM_MULT#(SHOPMENU_ABILITY,ABILITY_SPIN)=0.9

SHOPITEM_PRICE(SHOPMENU_ABILITY,ABILITY_ENDLESSGAUGE)=5000
SHOPITEM_NAME$(SHOPMENU_ABILITY,ABILITY_ENDLESSGAUGE)="Endless Gauge"
SHOPITEM_DESC1$(SHOPMENU_ABILITY,ABILITY_ENDLESSGAUGE)="The gauge never depletes however"
SHOPITEM_DESC2$(SHOPMENU_ABILITY,ABILITY_ENDLESSGAUGE)="you can not collect any rings."
SHOPITEM_MULT#(SHOPMENU_ABILITY,ABILITY_ENDLESSGAUGE)=0.5

SHOPITEM_PRICE(SHOPMENU_ABILITY,ABILITY_SPARECHANGE)=1250
SHOPITEM_NAME$(SHOPMENU_ABILITY,ABILITY_SPARECHANGE)="Spare Change"
SHOPITEM_DESC1$(SHOPMENU_ABILITY,ABILITY_SPARECHANGE)="You can now recover 30 extra rings when you are hit."
SHOPITEM_DESC2$(SHOPMENU_ABILITY,ABILITY_SPARECHANGE)=""
SHOPITEM_MULT#(SHOPMENU_ABILITY,ABILITY_SPARECHANGE)=0.9

;Skills
SHOPITEM_PRICE(SHOPMENU_SKILL,SKILL_SHIELD)=1000
SHOPITEM_NAME$(SHOPMENU_SKILL,SKILL_SHIELD)="Shield"
SHOPITEM_DESC1$(SHOPMENU_SKILL,SKILL_SHIELD)="Use Extra Skill to activate"
SHOPITEM_DESC2$(SHOPMENU_SKILL,SKILL_SHIELD)="a Shield once per Stage."
SHOPITEM_MULT#(SHOPMENU_SKILL,SKILL_SHIELD)=0.9

SHOPITEM_PRICE(SHOPMENU_SKILL,SKILL_FSHIELD)=1500
SHOPITEM_NAME$(SHOPMENU_SKILL,SKILL_FSHIELD)="Flame Shield"
SHOPITEM_DESC1$(SHOPMENU_SKILL,SKILL_FSHIELD)="Use Extra Skill to activate"
SHOPITEM_DESC2$(SHOPMENU_SKILL,SKILL_FSHIELD)="a Flame Shield once per Stage."
SHOPITEM_MULT#(SHOPMENU_SKILL,SKILL_FSHIELD)=0.9

SHOPITEM_PRICE(SHOPMENU_SKILL,SKILL_BSHIELD)=1500
SHOPITEM_NAME$(SHOPMENU_SKILL,SKILL_BSHIELD)="Bubble Shield"
SHOPITEM_DESC1$(SHOPMENU_SKILL,SKILL_BSHIELD)="Use Extra Skill to activate"
SHOPITEM_DESC2$(SHOPMENU_SKILL,SKILL_BSHIELD)="a Bubble Shield once per Stage."
SHOPITEM_MULT#(SHOPMENU_SKILL,SKILL_BSHIELD)=0.9

SHOPITEM_PRICE(SHOPMENU_SKILL,SKILL_TSHIELD)=1500
SHOPITEM_NAME$(SHOPMENU_SKILL,SKILL_TSHIELD)="Lightning Shield"
SHOPITEM_DESC1$(SHOPMENU_SKILL,SKILL_TSHIELD)="Use Extra Skill to activate"
SHOPITEM_DESC2$(SHOPMENU_SKILL,SKILL_TSHIELD)="a Lightning Shield once per Stage."
SHOPITEM_MULT#(SHOPMENU_SKILL,SKILL_TSHIELD)=0.9

SHOPITEM_PRICE(SHOPMENU_SKILL,SKILL_ESHIELD)=1500
SHOPITEM_NAME$(SHOPMENU_SKILL,SKILL_ESHIELD)="Earth Shield"
SHOPITEM_DESC1$(SHOPMENU_SKILL,SKILL_ESHIELD)="Use Extra Skill to activate"
SHOPITEM_DESC2$(SHOPMENU_SKILL,SKILL_ESHIELD)="an Earth Shield once per Stage."
SHOPITEM_MULT#(SHOPMENU_SKILL,SKILL_ESHIELD)=0.9

SHOPITEM_PRICE(SHOPMENU_SKILL,SKILL_BOOST)=42069
SHOPITEM_NAME$(SHOPMENU_SKILL,SKILL_BOOST)="Boost"
SHOPITEM_DESC1$(SHOPMENU_SKILL,SKILL_BOOST)="Use Extra Skill to boost"
SHOPITEM_DESC2$(SHOPMENU_SKILL,SKILL_BOOST)="at supersonic speeds!"
SHOPITEM_MULT#(SHOPMENU_SKILL,SKILL_BOOST)=0.75

SHOPITEM_PRICE(SHOPMENU_SKILL,SKILL_DROPDASH)=3000
SHOPITEM_NAME$(SHOPMENU_SKILL,SKILL_DROPDASH)="Drop Dash"
SHOPITEM_DESC1$(SHOPMENU_SKILL,SKILL_DROPDASH)="Hold extra skill in the air to"
SHOPITEM_DESC2$(SHOPMENU_SKILL,SKILL_DROPDASH)="rev up a dash when you hit the ground."
SHOPITEM_MULT#(SHOPMENU_SKILL,SKILL_DROPDASH)=0.8

SHOPITEM_PRICE(SHOPMENU_SKILL,SKILL_ISHIELD)=1500
SHOPITEM_NAME$(SHOPMENU_SKILL,SKILL_ISHIELD)="Insta-Shield"
SHOPITEM_DESC1$(SHOPMENU_SKILL,SKILL_ISHIELD)="Use Extra Skill to activate"
SHOPITEM_DESC2$(SHOPMENU_SKILL,SKILL_ISHIELD)="an attack affected by your shield."
SHOPITEM_MULT#(SHOPMENU_SKILL,SKILL_ISHIELD)=0.9

SHOPITEM_PRICE(SHOPMENU_SKILL,SKILL_CHAO)=3000
SHOPITEM_NAME$(SHOPMENU_SKILL,SKILL_CHAO)="Chocola"
SHOPITEM_DESC1$(SHOPMENU_SKILL,SKILL_CHAO)="Press extra skill to command"
SHOPITEM_DESC2$(SHOPMENU_SKILL,SKILL_CHAO)="Chocola to attack an enemy."
SHOPITEM_MULT#(SHOPMENU_SKILL,SKILL_CHAO)=0.8

SHOPITEM_PRICE(SHOPMENU_SKILL,SKILL_DOUBLEJUMP)=2500
SHOPITEM_NAME$(SHOPMENU_SKILL,SKILL_DOUBLEJUMP)="Double Jump"
SHOPITEM_DESC1$(SHOPMENU_SKILL,SKILL_DOUBLEJUMP)="Press extra skill to jump a second time."
SHOPITEM_MULT#(SHOPMENU_SKILL,SKILL_DOUBLEJUMP)=0.8

;Handicap
SHOPITEM_PRICE(SHOPMENU_HANDICAP,HANDICAP_NOROLL)=1000
SHOPITEM_NAME$(SHOPMENU_HANDICAP,HANDICAP_NOROLL)="Back pains"
SHOPITEM_DESC1$(SHOPMENU_HANDICAP,HANDICAP_NOROLL)="You are unable to charge a dash or"
SHOPITEM_DESC2$(SHOPMENU_HANDICAP,HANDICAP_NOROLL)="use the roll button."
SHOPITEM_MULT#(SHOPMENU_HANDICAP,HANDICAP_NOROLL)=1.3

SHOPITEM_PRICE(SHOPMENU_HANDICAP,HANDICAP_NOJUMP)=1000
SHOPITEM_NAME$(SHOPMENU_HANDICAP,HANDICAP_NOJUMP)="Shattered Ankles"
SHOPITEM_DESC1$(SHOPMENU_HANDICAP,HANDICAP_NOJUMP)="You cannot use jump, bounce"
SHOPITEM_DESC2$(SHOPMENU_HANDICAP,HANDICAP_NOJUMP)=" or jump actions"
SHOPITEM_MULT#(SHOPMENU_HANDICAP,HANDICAP_NOJUMP)=3.0

SHOPITEM_PRICE(SHOPMENU_HANDICAP,HANDICAP_DAREDEVIL)=1000
SHOPITEM_NAME$(SHOPMENU_HANDICAP,HANDICAP_DAREDEVIL)="Daredevil"
SHOPITEM_DESC1$(SHOPMENU_HANDICAP,HANDICAP_DAREDEVIL)="You die in one hit."
SHOPITEM_DESC2$(SHOPMENU_HANDICAP,HANDICAP_DAREDEVIL)="No exceptions."
SHOPITEM_MULT#(SHOPMENU_HANDICAP,HANDICAP_DAREDEVIL)=2.0

;Cosmetic
SHOPITEM_PRICE(SHOPMENU_COSMETIC,COSMETIC_BIGHEAD)=1000
SHOPITEM_NAME$(SHOPMENU_COSMETIC,COSMETIC_BIGHEAD)="Big-Head"
SHOPITEM_DESC1$(SHOPMENU_COSMETIC,COSMETIC_BIGHEAD)="Makes your head and arms gigantic."
SHOPITEM_DESC2$(SHOPMENU_COSMETIC,COSMETIC_BIGHEAD)="go bananas!"
SHOPITEM_MULT#(SHOPMENU_COSMETIC,COSMETIC_BIGHEAD)=1.0

SHOPITEM_PRICE(SHOPMENU_COSMETIC,COSMETIC_FLATCHARS)=1000
SHOPITEM_NAME$(SHOPMENU_COSMETIC,COSMETIC_FLATCHARS)="Blaze's Chest"
SHOPITEM_DESC1$(SHOPMENU_COSMETIC,COSMETIC_FLATCHARS)="Flattens your character into."
SHOPITEM_DESC2$(SHOPMENU_COSMETIC,COSMETIC_FLATCHARS)="a pancake."
SHOPITEM_MULT#(SHOPMENU_COSMETIC,COSMETIC_FLATCHARS)=1.0

SHOPITEM_PRICE(SHOPMENU_COSMETIC,COSMETIC_INVIS)=1000
SHOPITEM_NAME$(SHOPMENU_COSMETIC,COSMETIC_INVIS)="Classic Sonic"
SHOPITEM_DESC1$(SHOPMENU_COSMETIC,COSMETIC_INVIS)="Hides your model completely,"
SHOPITEM_DESC2$(SHOPMENU_COSMETIC,COSMETIC_INVIS)="leaving just a Shadow"
SHOPITEM_MULT#(SHOPMENU_COSMETIC,COSMETIC_INVIS)=1.0

;Consumables
SHOPITEM_PRICE(SHOPMENU_CONSUME,CONSUME_LIFE)=250
SHOPITEM_NAME$(SHOPMENU_CONSUME,CONSUME_LIFE)="Extra Life"
SHOPITEM_DESC1$(SHOPMENU_CONSUME,CONSUME_LIFE)="Can't be bothered to get 100 rings"
SHOPITEM_DESC1$(SHOPMENU_CONSUME,CONSUME_LIFE)="in a stage? You're in luck."

SHOPITEM_PRICE(SHOPMENU_CONSUME,CONSUME_EMBLEM)=2500
SHOPITEM_NAME$(SHOPMENU_CONSUME,CONSUME_EMBLEM)="Extra Emblem"
SHOPITEM_DESC1$(SHOPMENU_CONSUME,CONSUME_EMBLEM)="Just shy of unlocking that character"
SHOPITEM_DESC2$(SHOPMENU_CONSUME,CONSUME_EMBLEM)="that your in need of? This will help."

SHOPITEM_PRICE(SHOPMENU_CONSUME,CONSUME_REDRING)=500
SHOPITEM_NAME$(SHOPMENU_CONSUME,CONSUME_REDRING)="Extra Token"
SHOPITEM_DESC1$(SHOPMENU_CONSUME,CONSUME_REDRING)="Curious as to what other secrets the island"
SHOPITEM_DESC2$(SHOPMENU_CONSUME,CONSUME_REDRING)="holds? Why don't you find out"






;~IDEal Editor Parameters:
;~C#Blitz3D
;~IDEal Editor Parameters:
;~C#Blitz3D