; /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
; /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/

	; --- Collisions constants ---
Const COLLISION_NONE						=	0
Const COLLISION_PLAYER						=	1
Const COLLISION_OBJECT						=	2
Const COLLISION_OBJECT2						=	3
Const COLLISION_OBJECT_GOTHRU				=	4
Const COLLISION_OBJECT2_GOTHRU				=	5
Const COLLISION_CAMERA						=	6
Const COLLISION_WORLD_POLYGON				=	7
Const COLLISION_WORLD_POLYGON_DEATH			=	8
Const COLLISION_WORLD_POLYGON_DEATH_GOTHRU	=	9
Const COLLISION_WORLD_POLYGON_HURT			=	10
Const COLLISION_WORLD_POLYGON_RAIL			=	11
Const COLLISION_WORLD_POLYGON_BLOCK			=	12
Const COLLISION_WORLD_POLYGON_PINBALL		=	13
Const COLLISION_WORLD_POLYGON_ICE			=	14
Const COLLISION_WORLD_POLYGON_BOUNCE		=	15
Const COLLISION_WORLD_POLYGON_SLOW			=	16
Const COLLISION_WORLD_POLYGON_DIRT				=	17
Const COLLISION_WORLD_POLYGON_GRASS				=	18
Const COLLISION_WORLD_POLYGON_METAL				=	19
Const COLLISION_WORLD_POLYGON_WOOD				=	20
Const COLLISION_WORLD_POLYGON_WATER				=	21
Const COLLISION_OBJECT_TELEPORTER			=	22
Const COLLISION_GRINDAFFECTOR		=	23
Const COLLISION_WORLD_POLYGON_RUN = 24
Const COLLISION_WORLD_POLYGON_WATER2 = 25
Const COLLISION_WORLD_POLYGON_ROLL = 26

Function Game_Stage_SetCollisions()
		; Setup collisions within the environment.
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_WATER, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_WATER2, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_DIRT, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_GRASS, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_WOOD, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_METAL, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_DEATH, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_HURT, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_RAIL, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_BLOCK, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_PINBALL, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_ICE, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_BOUNCE, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_SLOW, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_RUN, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_WORLD_POLYGON_ROLL, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_PLAYER, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_OBJECT, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_OBJECT2, 2, 2)
	Collisions(COLLISION_PLAYER, COLLISION_OBJECT_TELEPORTER, 2, 2)
	
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON_RUN, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON_WATER, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON_DIRT, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON_GRASS, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON_WOOD, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON_METAL, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON_DEATH, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON_HURT, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON_BLOCK, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON_PINBALL, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON_ICE, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON_BOUNCE, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_WORLD_POLYGON_SLOW, 2, 2)
	Collisions(COLLISION_CAMERA, COLLISION_PLAYER, 2, 2)
	
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_ROLL, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_RUN, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_WATER, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_DIRT, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_GRASS, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_WOOD, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_METAL, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_DEATH, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_HURT, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_RAIL, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_BLOCK, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_PINBALL, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_ICE, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_BOUNCE, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_WORLD_POLYGON_SLOW, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_PLAYER, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_OBJECT, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_OBJECT_TELEPORTER, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_OBJECT_GOTHRU, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_OBJECT2, 2, 3)
	Collisions(COLLISION_OBJECT, COLLISION_OBJECT2_GOTHRU, 2, 3)
	
	
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_ROLL, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_RUN, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_WATER, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_DIRT, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_GRASS, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_WOOD, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_METAL, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_DEATH, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_HURT, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_RAIL, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_BLOCK, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_PINBALL, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_ICE, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_BOUNCE, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_WORLD_POLYGON_SLOW, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_PLAYER, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_OBJECT, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_OBJECT_TELEPORTER, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_OBJECT_GOTHRU, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_OBJECT2, 2, 2)
	Collisions(COLLISION_OBJECT2, COLLISION_OBJECT2_GOTHRU, 2, 2)
	
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_ROLL, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_RUN, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_WATER, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_DIRT, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_GRASS, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_WOOD, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_METAL, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_DEATH, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_HURT, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_RAIL, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_BLOCK, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_PINBALL, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_ICE, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_BOUNCE, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_WORLD_POLYGON_SLOW, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_PLAYER, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_OBJECT, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_OBJECT_TELEPORTER, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_OBJECT_GOTHRU, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_OBJECT2, 2, 3)
	Collisions(COLLISION_OBJECT_GOTHRU, COLLISION_OBJECT2_GOTHRU, 2, 3)
	
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_ROLL, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_RUN, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_WATER, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_DIRT, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_GRASS, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_WOOD, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_METAL, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_DEATH, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_HURT, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_RAIL, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_BLOCK, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_PINBALL, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_ICE, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_BOUNCE, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_WORLD_POLYGON_SLOW, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_PLAYER, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_OBJECT, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_OBJECT_TELEPORTER, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_OBJECT_GOTHRU, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_OBJECT2, 2, 2)
	Collisions(COLLISION_OBJECT2_GOTHRU, COLLISION_OBJECT2_GOTHRU, 2, 2)
	
	Collisions(COLLISION_GRINDAFFECTOR, COLLISION_WORLD_POLYGON_RAIL, 			2, 2)
End Function

Function Game_Stage_ResetProperties()
	Game\ResetCollectibles=1
	Game\Stage\Properties\Fog = 0
	Game\Stage\Properties\FogR = 0
	Game\Stage\Properties\FogG = 0 
	Game\Stage\Properties\FogB  = 0
	Game\Stage\Properties\FogNearDist = 0
	Game\Stage\Properties\FogFarDist = 0
	Game\Stage\Properties\Hub = 0
	
	Game\Stage\Properties\MusicStyle=0
	
	Game\Stage\Properties\Earth = CopyEntity(MESHES(Mesh_Empty))
	Game\Stage\Properties\Moon = CopyEntity(MESHES(Mesh_Empty))
	Game\Stage\Properties\Sun = CopyEntity(MESHES(Mesh_Empty))
	
	Game\Stage\Properties\SunPos = New tVector
	Game\Stage\Properties\SunPos\x#=0
	Game\Stage\Properties\SunPos\y#=0
	Game\Stage\Properties\SunPos\z#=0
	
	Game\Stage\Properties\FilterOn = 0
	Game\Stage\Properties\FilterIntesity# = 1.0 	
	Game\Stage\Properties\FilterR = 0
	Game\Stage\Properties\FilterG  = 0
	Game\Stage\Properties\FilterB  = 0
	
	Game\Stage\Properties\Water=0
	Game\Stage\Properties\WaterType=1
	Game\Stage\Properties\WaterLevel = -99999
	Game\Stage\Properties\WaterLevelInitial = 0
	Game\Stage\Properties\WaterLevelTarget = 0
	Game\Stage\Properties\WaterLevelChanged = 0
	Game\Stage\Properties\DeathLevel = -2500
	Game\Stage\Properties\AmbientAlarm = 0
	Game\Stage\Properties\AmbientBeach = 0
	Game\Stage\Properties\AmbientForest = 0
	Game\Stage\Properties\AmbientRain = 0
	Game\Stage\Properties\AmbientSnow = 0
	Game\Stage\Properties\AmbientVoid = 0
	Game\Stage\Properties\AmbientWind = 0
	
	Game\Stage\Properties\StartX#=0
	Game\Stage\Properties\StartY#=0
	Game\Stage\Properties\StartZ#=0
	Game\Stage\Properties\StartDirection#=0
	
	Game\Stage\Properties\AmbientParticle = ParticleTemplate_Create.tParticleTemplate()
	
	
	Game\Gameplay\CurrentLapCheck=1
	Game\Gameplay\CurrentLap=1
	Game\Gameplay\TotalLapCheck=1
	Game\CollectibleCount=0
	
	
	Game\MissionValue=3 	
	
	Game\ResultRings=0
	Game\ResultRingsForBank=0
	Game\ResultEnemies=0
	Game\ResultTime=5999999
	Game\ResultPerfectBonus=0
	Game\ScoreBonus=0
	Game\ScoreTotal=0
	Game\Rank=7
	Game\RivalAmount=0
	Game\InsideBoxCheckerTimer=0
	Game\WholeVehicle=0
	
	Game\UsedSkill=0
	
End Function
;~IDEal Editor Parameters:
;~C#Blitz3D